package model

type ShoperOrder struct {
	OrderId          string      `json:"order_id"`
	UserId           string      `json:"user_id"`
	Date             string      `json:"date"`
	StatusDate       string      `json:"status_date"`
	ConfirmDate      string      `json:"confirm_date"`
	DeliveryDate     string      `json:"delivery_date"`
	StatusId         string      `json:"status_id"`
	Sum              string      `json:"sum"`
	PaymentId        string      `json:"payment_id"`
	UserOrder        string      `json:"user_order"`
	ShippingId       string      `json:"shipping_id"`
	ShippingCost     string      `json:"shipping_cost"`
	Email            string      `json:"email"`
	DeliveryCode     string      `json:"delivery_code"`
	Code             string      `json:"code"`
	Confirm          string      `json:"confirm"`
	Notes            string      `json:"notes"`
	NotesPriv        string      `json:"notes_priv"`
	NotesPub         string      `json:"notes_pub"`
	CurrencyId       string      `json:"currency_id"`
	CurrencyRate     string      `json:"currency_rate"`
	Paid             string      `json:"paid"`
	IpAddress        string      `json:"ip_address"`
	DiscountClient   string      `json:"discount_client"`
	DiscountGroup    string      `json:"discount_group"`
	DiscountLevels   string      `json:"discount_levels"`
	DiscountCode     string      `json:"discount_code"`
	ShippingVat      string      `json:"shipping_vat"`
	ShippingVatValue string      `json:"shipping_vat_value"`
	ShippingVatName  string      `json:"shipping_vat_name"`
	CodeId           interface{} `json:"code_id"`
	LangId           string      `json:"lang_id"`
	Origin           string      `json:"origin"`
	ParentOrderId    interface{} `json:"parent_order_id"`
	Registered       string      `json:"registered"`
	BillingAddress   struct {
		AddressId   string `json:"address_id"`
		OrderId     string `json:"order_id"`
		Type        string `json:"type"`
		Firstname   string `json:"firstname"`
		Lastname    string `json:"lastname"`
		Company     string `json:"company"`
		TaxId       string `json:"tax_id"`
		Pesel       string `json:"pesel"`
		City        string `json:"city"`
		Postcode    string `json:"postcode"`
		Street1     string `json:"street1"`
		Street2     string `json:"street2"`
		State       string `json:"state"`
		Country     string `json:"country"`
		Phone       string `json:"phone"`
		CountryCode string `json:"country_code"`
	} `json:"billingAddress"`
	DeliveryAddress struct {
		AddressId   string `json:"address_id"`
		OrderId     string `json:"order_id"`
		Type        string `json:"type"`
		Firstname   string `json:"firstname"`
		Lastname    string `json:"lastname"`
		Company     string `json:"company"`
		TaxId       string `json:"tax_id"`
		Pesel       string `json:"pesel"`
		City        string `json:"city"`
		Postcode    string `json:"postcode"`
		Street1     string `json:"street1"`
		Street2     string `json:"street2"`
		State       string `json:"state"`
		Country     string `json:"country"`
		Phone       string `json:"phone"`
		CountryCode string `json:"country_code"`
	} `json:"deliveryAddress"`
	CurrencyName string `json:"currency_name"`
	Shipping     struct {
		ShippingId    string `json:"shipping_id"`
		Cost          string `json:"cost"`
		DependOnW     string `json:"depend_on_w"`
		TaxId         string `json:"tax_id"`
		MaxWeight     string `json:"max_weight"`
		MinWeight     string `json:"min_weight"`
		FreeShipping  string `json:"free_shipping"`
		Order         string `json:"order"`
		Pkwiu         string `json:"pkwiu"`
		Mobile        string `json:"mobile"`
		Engine        string `json:"engine"`
		ZoneId        string `json:"zone_id"`
		CallbackUrl   string `json:"callback_url"`
		WarehouseId   bool   `json:"warehouse_id"`
		TranslationId string `json:"translation_id"`
		Name          string `json:"name"`
		Description   string `json:"description"`
		IsDefault     string `json:"is_default"`
	} `json:"shipping"`
	Status struct {
		StatusId    string `json:"status_id"`
		Default     string `json:"default"`
		Color       string `json:"color"`
		Type        string `json:"type"`
		EmailChange string `json:"email_change"`
		Order       string `json:"order"`
		Name        string `json:"name"`
		Message     string `json:"message"`
	} `json:"status"`
	Payment struct {
		PaymentId   string `json:"payment_id"`
		Name        string `json:"name"`
		Order       string `json:"order"`
		Title       string `json:"title"`
		Description string `json:"description"`
		NotifyMail  string `json:"notify_mail"`
	} `json:"payment"`
	PromoCode string `json:"promo_code"`
	Products  []struct {
		Id                string        `json:"id"`
		OrderId           string        `json:"order_id"`
		ProductId         string        `json:"product_id"`
		StockId           string        `json:"stock_id"`
		Price             string        `json:"price"`
		DiscountPerc      string        `json:"discount_perc"`
		Quantity          string        `json:"quantity"`
		DeliveryTime      int           `json:"delivery_time"`
		Name              string        `json:"name"`
		Code              string        `json:"code"`
		Pkwiu             string        `json:"pkwiu"`
		Tax               string        `json:"tax"`
		TaxValue          string        `json:"tax_value"`
		Unit              string        `json:"unit"`
		Option            string        `json:"option"`
		UnitFp            string        `json:"unit_fp"`
		Weight            string        `json:"weight"`
		Type              string        `json:"type"`
		Loyalty           string        `json:"loyalty"`
		DeliveryTimeHours string        `json:"delivery_time_hours"`
		TextOptions       []interface{} `json:"text_options"`
		FileOptions       []interface{} `json:"file_options"`
	} `json:"products"`
	AdditionalFields []struct {
		FieldId string `json:"field_id"`
		Type    string `json:"type"`
		Locate  string `json:"locate"`
		Req     string `json:"req"`
		Active  string `json:"active"`
		Order   string `json:"order"`
		Value   string `json:"value"`
	} `json:"additional_fields"`
	Children []interface{} `json:"children"`
}
